### ISSUE TITLE
Unable to open wider_face_train.mat file with h5py in st_face.py

### ISSUE THREAD

**Issue by lynnw123** [kensun0/Face-Detecion-with-the-Faster-R-CNN-R-FCN#6]
Thanks for the amazing face detector models! I am trying to train the R-FCN face detection models with WIDER datasets using st_face.py and factory.py you provided. I also modified 2 paths in st_face.py (f and prefix) to my own path. however,  imdb, roidb = combined_roidb(args.imdb_name) failed since could not able to create imdb.

f = h5py.File('/data/st/data/wider/wider_face_train.mat')
the output is following:
.........            
.........
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Traceback (most recent call last):
  File "./tools/train_net_wider.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net_wider.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net_wider.py", line 62, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/yl/hd/detection/py-R-FCN/tools/../lib/datasets/factory.py", line 41, in get_imdb
    return __sets[name]()
  File "/home/yl/hd/detection/py-R-FCN/tools/../lib/datasets/st_face.py", line 31, in __init__
    self._image_index, self._bbx_index = self._load_image_set_index()
  File "/home/yl/hd/detection/py-R-FCN/tools/../lib/datasets/st_face.py", line 46, in _load_image_set_index
    f = h5py.File('/home/yl/hd/facedetect/wider/wider_face_split/wider_face_train.mat', 'r')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
IOError: Unable to open file (File signature not found)

the message "File signature not found" suggests the file is either corrupted or not in the HDF5 format, then I used h5debug to check the hdf5 utilities and the out is:

h5debug wider_face_train.mat 
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140126050862848:
  #000: ../../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file

Do I in the wrong way to create the imdb of WIDER dataset based on your scripts? Any suggestions are greatly appreciated!

**Comment by tobiasbrechtelsbauer** [comment]
Hi Vmaxx-yinling, 
I had the same problem. 
My solution was to load the wider_face_train.mat into Matlab and save the variables to a new .mat file by using the save() function from Matlab. You will also have to specify the version of the new .mat file to '-v7.3'.
